version: 0.0
os: linux

files:
  - source: target/superhero-api-0.0.3-SNAPSHOT.jar
    destination: /tmp

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: ec2-user
